In [1]:
import numpy as np

In [5]:
a = np.arange(24).reshape(2,3,4)
print(a)
print(np.mean(a))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
11.5


In [4]:
a = np.arange(24).reshape(2,3,4)
print(a)
a = a.reshape(2,12)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]
